#This is an example of what an MCGTools config might look like

directories: #These are the directories for DIRector to create
  Cam_1: []
  Cam_2: []
  Cam_3: []
  Cam_4: []
  Cam_5: []
  PGM: []
  HELO: []
  Stream: 
    vimeo: []
    youtube: []


files: #These are files for gogetter to go get

  -
    url: 'http://212.183.159.230/100MB.zip' #URL of the file to be downloaded
    dir: 'Cam_1' #Director to store the file in

  -
    url: 'http://212.183.159.230/100MB.zip'
    dir: 'Cam_1'

  -
    url: 'http://212.183.159.230/100MB.zip'
    dir: 'Cam_2'

  -
    url: 'http://212.183.159.230/100MB.zip'
    dir: 'Cam_2'

  -
    url: 'http://212.183.159.230/100MB.zip'
    dir: 'Cam_3'

  -
    url: 'http://212.183.159.230/100MB.zip'
    dir: 'Cam_3'

  -
    url: 'http://212.183.159.230/100MB.zip'
    dir: 'Cam_4'

  -
    url: 'http://212.183.159.230/100MB.zip'
    dir: 'Cam_4'

  -
    url: 'http://212.183.159.230/100MB.zip'
    dir: 'PGM'

  -
    url: 'http://212.183.159.230/100MB.zip'
    dir: 'PGM'