services:

  map_ingest:
    build:
      context: .
      dockerfile: ingest_server.Dockerfile
    ports:
      - 8000:8000
    volumes:
      - /mnt/jazz_repository:/jazz_repository
      - /mnt/pt_shows:/pt_shows
    environment:
      SERVER_ADDRESS: "http://<Server Address>"
      DB_CONNECT_STRING: "<MongoConnectString>"
      DB_NAME: "<DB Name>"

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ingest_ui/nginx.conf:/etc/nginx/nginx.conf
      - /ingest_ui/static:/usr/share/nginx/html:ro

    environment:
      - API_SERVER_ADDRESS="http://<Server Address>:8000/"
    command: sh -c "envsubst < /etc/nginx/nginx.conf > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"